-- :fennel:1728206146
vim.g.mapleader = " "
vim.g.maplocalleader = " "
local _local_1_ = require("my.utils")
local map_21 = _local_1_["map!"]
map_21("n", "<Leader>bn", ":bn<cr>", "Next buffer")
map_21("n", "<Leader>bp", ":bp<cr>", "Previous buffer")
map_21("n", "<Leader>bb", ":b#<cr>", "Last visited buffer")
map_21("n", "<Leader>bx", ":bd!<cr>", "Close buffer")
map_21("n", "<Leader>s", ":split<cr>", "Horizontal split")
map_21("n", "<Leader>v", ":vsplit<cr>", "Vertical split")
map_21("n", "<Leader>wx", ":close<cr>", "Close window")
map_21("ni", "<C-h>", "<ESC><C-W>h", "Move between windows")
map_21("ni", "<C-j>", "<ESC><C-W>j", "Move between windows")
map_21("ni", "<C-k>", "<ESC><C-W>k", "Move between windows")
map_21("ni", "<C-l>", "<ESC><C-W>l", "Move between windows")
map_21("ni", "<A-k>", "<cmd>m .-2<cr>", "Move line up")
map_21("v", "<A-k>", ":m '<-2<cr>gv", "Move line up")
map_21("ni", "<A-j>", "<cmd>m .+1<cr>", "Move line down")
map_21("v", "<A-j>", ":m '>+1<cr>gv", "Move line down")
map_21("v", "<", "<gv", "Visual Indent")
map_21("v", ">", ">gv", "Visual Indent")
map_21("nv", "<Leader>y", "\"+yy<esc>", "Copy to system clipboard")
map_21("nv", "<Leader>p", "\"+p", "Paste from system clipboard")
map_21("n", "<Esc>", "<cmd>noh<cr>", {desc = "Clears search highlights", silent = true})
map_21("ni", "<C-s>", "<cmd>w<cr>", "Save file")
map_21("nv", "<Leader><Leader>", ":", "Command-line mode")
map_21("nv", "<Leader>f", "/", "Search mode")
return map_21("t", "<Esc><Esc>", "<C-\\><C-n>", "Escape terminal mode")